apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleexpress
  labels:
    app: simpleexpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleexpress
  template:
    metadata:
      labels:
        app: simpleexpress
    spec:
      containers:
      - name: simpleexpress
        image: ludaman64/simple-express
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
