apiVersion: v1
kind: Service
metadata:
  labels:
    service: simpleexpress
  name: simpleexpress-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: simpleexpress
